#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount sv systemctl pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkdir="mkdir -pv" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	e="$EDITOR" \
	v="$EDITOR" \
	ll="ls -lh" \
	l="ls -lh" \
	la="ls -lah" \
	n="nnn" \
	t="tmux attach || tmux" \
	dots="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
